Analysis: Create missing switch cases for taxonomy xmlrpc client errors
Error: "'switch' statement on enum type
'org.wordpress.android.fluxc.network.BaseRequest.GenericErrorType'
misses cases: 'TIMEOUT', 'NO_CONNECTION', 'NETWORK_ERROR', 'NOT_FOUND',
'CENSORED', 'SERVER_ERROR', 'INVALID_SSL_CERTIFICATE',
'HTTP_AUTH_ERROR', 'INVALID_RESPONSE', 'NOT_AUTHENTICATED',
'PARSE_ERROR' and 'UNKNOWN'"