Deps: add back eventbus android dependency
This dependency was incorrectly removed and replaced by its
corresponding 'eventbus-java' transitive dependency, assuming that is
not required. However, after further testing it was revealed that this
parent 'eventbus' dependency, which is actually 'android' specific is
indeed necessary. If it is not provided on the classpath then an app
will crash with the below runtime exception:

------------------------------------------------------------------------

java.lang.RuntimeException: Unable to create application xyz: java.lang
.RuntimeException: It looks like you are using EventBus on Android,
make sure to add the "eventbus" Android library to your dependencies.

------------------------------------------------------------------------

For more info see:
- EventBus.register(...): https://github.com/greenrobot/EventBus/blob/
0194926b3bcf70cc0d7bfd3c5da16708dd5ab876/EventBus/src/org/greenrobot/
eventbus/EventBus.java#L143-L147
- !AndroidDependenciesDetector.areAndroidComponentsAvailable():
https://github.com/greenrobot/EventBus/blob/
0194926b3bcf70cc0d7bfd3c5da16708dd5ab876/EventBus/src/org/greenrobot/
eventbus/android/AndroidDependenciesDetector.java#L25-L36